language: objective-c
osx_image: xcode7.2
xcode_project: SKTaskUtils.xcodeproj
xcode_scheme: SKTaskUtils
xcode_sdk: iphonesimulator
before_install:
before_script:
- carthage bootstrap --platform iOS
before_deploy:
- carthage build --no-skip-current --platform iOS
- carthage archive SKTaskUtils
deploy:
  provider: releases
  api_key:
    secure: mg1h+BbXkVI3sR8/fX/Zgcx42cOp/scGq9rRKonEl9ztDau1jVVUPRx1RH9uaAoEbTKl0Q+FWL/n9w1Ak7KPWMKbkHW3sEwqdXYqCbNiUECdtv8JkuNhf0e4XOeMtY5GC1gmoGVQQfiThhb7D2v+I4D7loHatdDA8pjYmDuJxYb4oN5Dkr7Sc8Yf3TjsyGafG74pcH4q9CrRPTtUYXVKfDjqM4XK62OeuCftlHVNNdnow7SDfR1fMbcnfsD0pA5BJpP5itvPKsmfa9TGV/mh+19Qi8A5lDwJ+AzPQ49JIOdxZ6tCxcxE34GmSG+Ut3YR3cVyrCm5MFROc0HGaEsPZ/f44VoIVQmGOUM3KHeYtpQmONqH6k7MY1BYkDqMrvOWz200RMYplM9zJFDC6iSN3tDb9m3HKzn0ZmAYbSVQY3yC0+o7SKb2aETWrA7qfqxQMiVFuXl1T2X106T7nQrwK3TSI8HS9ewM5OJC3gXL3jsiZu+fStAWzMGbmYj7r+4TGBxYvoHDPiPGBWEera11jvIAE5oo59w78PO2/41tasjJdwdTkx/TOfSuSdyUS6gK94DUsWAD/DENnqRFW5g3xDdVZOyuy9jD7hIgHQYFgGX0xV877NpDrfgRFLRWt8iXnFJJmEoDTVv8rhEacLxPLs6tbkoULKQR3DFrS8ghgHE=
  file: SKTaskUtils.framework.zip
  skip_cleanup: true
  on:
    repo: skchen/SKTaskUtils
    tags: true
